name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi,\n\nThanks for taking the time to log an issue! We will get to you shortly. We try to be responsive.'
        pr-message: 'Hi,\n\nThanks for taking the time to create a PR! We will get to you shortly. We try to be responsive.'
